In [17]:
import FinanceDataReader as fdr
import matplotlib.pyplot as plt
%matplotlib inline

import pandas as pd
import numpy as np
import requests
import bs4

pd.options.display.float_format = '{:,.3f}'.format

In [15]:
import datetime
today_dt = '2022-04-01'
today = datetime.datetime.strptime(today, '%Y-%m-%d')
start_dt = today - datetime.timedelta(days=100) # 100 일전 데이터 부터 시작 - 피쳐 엔지니어링은 최소 60 개의 일봉이 필요함

In [16]:
kosdaq_list = pd.read_pickle('kosdaq_list.pkl')

price_data = pd.DataFrame()

for code, name in zip(kosdaq_list['code'], kosdaq_list['name']):  # 코스닥 모든 종목에서 대하여 반복
    daily_price = fdr.DataReader(code,  start = start_dt, end = today_dt) # 종목, 일봉, 데이터 갯수
    daily_price['code'] = code
    daily_price['name'] = name
    price_data = pd.concat([price_data, daily_price], axis=0)   

price_data.index.name = 'date'
price_data.columns= price_data.columns.str.lower() # 컬럼 이름 소문자로 변경

In [20]:
kosdaq_index = fdr.DataReader('KQ11', start = start_dt, end = today_dt) # 데이터 호출
kosdaq_index.columns = ['close','open','high','low','volume','change'] # 컬럼명 변경
kosdaq_index.index.name='date' # 인덱스 이름 생성
kosdaq_index.sort_index(inplace=True) # 인덱스(날짜) 로 정렬 
kosdaq_index['kosdaq_return'] = kosdaq_index['close']/kosdaq_index['close'].shift(1) # 수익율 : 전 날 종가대비 당일 종가

In [21]:
merged = price_data.merge(kosdaq_index['kosdaq_return'], left_index=True, right_index=True, how='left')

In [28]:
return_all = pd.DataFrame()

for code in kosdaq_list['code']:  
    
    stock_return = merged[merged['code']==code].sort_index()
    stock_return['return'] = stock_return['close']/stock_return['close'].shift(1) # 종목별 전일 종가 대비 당일 종가 수익율
    c1 = (stock_return['kosdaq_return'] < 1) # 수익율 1 보다 작음. 당일 종가가 전일 종가보다 낮음 (코스닥 지표)
    c2 = (stock_return['return'] > 1) # 수익율 1 보다 큼. 당일 종가가 전일 종가보다 큼 (개별 종목)
    stock_return['win_market'] = np.where((c1&c2), 1, 0) # C1 과 C2 조건을 동시에 만족하면 1, 아니면 0
    return_all = pd.concat([return_all, stock_return], axis=0) 
    
return_all.dropna(inplace=True)

In [29]:
return_all.head()

,open,high,low,close,volume,change,code,name,kosdaq_return,return,win_market
date,,,,,,,,,,,
2021-12-23,3195,3260,3195,3220,104180,-0.002,060310,3S,1.003,0.998,0
2021-12-24,3230,3355,3220,3290,238933,0.022,060310,3S,1.004,1.022,0
2021-12-27,3290,3380,3275,3305,130826,0.005,060310,3S,1.004,1.005,0
2021-12-28,3355,3355,3180,3190,267316,-0.035,060310,3S,1.016,0.965,0
2021-12-29,3200,3350,3200,3330,115094,0.044,060310,3S,1.001,1.044,0

In [32]:
feature_all = pd.DataFrame()

for code, sector in zip(kosdaq_list['code'], kosdaq_list['sector']):

    data = return_all[return_all['code']==code].sort_index().copy()
    
    
    # 가격변동성이 크고, 거래량이 몰린 종목이 주가가 상승한다
    data['price_mean'] = data['close'].rolling(20).mean()
    data['price_std'] = data['close'].rolling(20).std(ddof=0)
    data['price_z'] = (data['close'] - data['price_mean'])/data['price_std']    
    data['volume_mean'] = data['volume'].rolling(20).mean()
    data['volume_std'] = data['volume'].rolling(20).std(ddof=0)
    data['volume_z'] = (data['close'] - data['volume_mean'])/data['volume_std']
    data = data[(data['price_std']>1) & (data['volume_std']>1)]      
    
    
    # 위꼬리가 긴 양봉이 자주발생한다.
    data['positive_candle'] = (data['close'] > data['open']).astype(int) # 양봉
    data['high/close'] = (data['positive_candle']==1)*(data['high']/data['close'] > 1.1).astype(int) # 양봉이면서 고가가 종가보다 높게 위치
    data['num_high/close'] =  data['high/close'].rolling(20).sum()
    data['long_candle'] = (data['positive_candle']==1)*(data['high']==data['close'])*\
    (data['low']==data['open'])*(data['close']/data['open'] > 1.2).astype(int) # 장대 양봉을 데이터로 표현
    data['num_long'] =  data['long_candle'].rolling(60).sum() # 지난 20 일 동안 장대양봉의 갯 수
    
    
     # 거래량이 종좀 터지며 매집의 흔적을 보인다   
    data['volume_mean'] = data['volume'].rolling(60).mean()
    data['volume_std'] = data['volume'].rolling(60).std()
    data['volume_z'] = (data['volume'] - data['volume_mean'])/data['volume_std'] # 거래량은 종목과 주가에 따라 다르기 떄문에 표준화한 값이 필요함
    data['z>1.96'] = (data['close'] > data['open'])*(data['volume_z'] > 1.65).astype(int) # 양봉이면서 거래량이 90%신뢰구간을 벗어난 날
    data['num_z>1.96'] =  data['z>1.96'].rolling(60).sum()  # 양봉이면서 거래량이 90% 신뢰구간을 벗어난 날을 카운트
    
    # 주가지수보다 더 좋은 수익율을 보여준다
    data['num_win_market'] = data['win_market'].rolling(60).sum() # 주가지수 수익율이 1 보다 작을 때, 종목 수익율이 1 보다 큰 날 수
    data['pct_win_market'] = (data['return']/data['kosdaq_return']).rolling(60).mean() # 주가지수 수익율 대비 종목 수익율
    
    
    # 동종업체 수익률보다 더 좋은 수익율을 보여준다.           
    data['return_mean'] = data['return'].rolling(60).mean() # 종목별 최근 60 일 수익율의 평균
    data['sector'] = sector

    feature_all = pd.concat([data, feature_all], axis=0)

feature_all['sector_return'] = feature_all.groupby(['sector', feature_all.index])['return'].transform(lambda x: x.mean()) # 섹터의 평균 수익율 계산
feature_all['return over sector'] = (feature_all['return']/feature_all['sector_return']) # 섹터 평균 수익률 대비 종목 수익률 계산
# feature_all.dropna(inplace=True) # Missing 값 있는 행 모두 제거


# 최종 피처만으로 구성
feature_all = feature_all[['code', 'sector','price_z','volume_z','num_high/close','num_long','num_z>1.96','num_win_market','pct_win_market','return over sector']]

In [33]:
feature_all

,code,sector,price_z,volume_z,num_high/close,num_long,num_z>1.96,num_win_market,pct_win_market,return over sector
date,,,,,,,,,,
2022-01-20,238490,특수 목적용 기계 제조업,-1.912,NaN,NaN,NaN,NaN,NaN,NaN,0.984
2022-01-21,238490,특수 목적용 기계 제조업,-2.140,NaN,NaN,NaN,NaN,NaN,NaN,0.998
2022-01-24,238490,특수 목적용 기계 제조업,-1.981,NaN,NaN,NaN,NaN,NaN,NaN,1.018
2022-01-25,238490,특수 목적용 기계 제조업,-2.059,NaN,NaN,NaN,NaN,NaN,NaN,1.005
2022-01-26,238490,특수 목적용 기계 제조업,-1.499,NaN,NaN,NaN,NaN,NaN,NaN,1.014
...,...,...,...,...,...,...,...,...,...,...
2022-03-28,060310,전자부품 제조업,0.478,NaN,0.000,NaN,NaN,NaN,NaN,0.997
2022-03-29,060310,전자부품 제조업,1.637,NaN,0.000,NaN,NaN,NaN,NaN,1.016
2022-03-30,060310,전자부품 제조업,3.966,NaN,0.000,NaN,NaN,NaN,NaN,1.117
2022-03-31,060310,전자부품 제조업,2.004,NaN,0.000,NaN,NaN,NaN,NaN,0.945
2022-04-01,060310,전자부품 제조업,2.329,NaN,0.000,NaN,NaN,NaN,NaN,1.035